In [31]:
import pandas as pd
import sqlite3 as lite
con=lite.connect("DBMS2_PROJECT")

In [ ]:
con.execute("create table userss (UserID INT PRIMARY KEY  ,Name VARCHAR(100) NOT NULL, Username VARCHAR(50),Email VARCHAR(100),Password VARCHAR(100)NOT NULL,JoinDate DATE,LastLogin TIMESTAMP )")

In [98]:
p=[ (1, 'John Smith', 'john123', 'john@example.com', 'hashed123', '2023-01-15', '2024-05-10 08:30:00'),
    (2, 'Emily Johnson', 'emily456', 'emily@example.com', 'hashed456', '2023-02-20', '2024-05-11 10:45:00'),
    (3, 'David Brown', 'david789', 'david@example.com', 'hashed789', '2023-03-25', '2024-05-12 12:15:00'),
    (4, 'james', 'james277', 'james@example.com', 'hashed277', '2023-04-30','2024-05-13 13:15:00'),
    (5, 'Alice', 'alice722', 'alice@example.com', 'hashed722', '2023-05-15','2024-05-14 14:30:00')];

In [ ]:
query= """INSERT INTO userss VALUES(?,?,?,?,?,?,?)"""
con.executemany(query,p)

In [100]:
pd.read_sql("Select * from userss",con)

,UserID,Name,Username,Email,Password,JoinDate,LastLogin
0,1,John Smith,john123,john@example.com,hashed123,2023-01-15,2024-05-10 08:30:00
1,2,Emily Johnson,emily456,emily@example.com,hashed456,2023-02-20,2024-05-11 10:45:00
2,3,David Brown,david789,david@example.com,hashed789,2023-03-25,2024-05-12 12:15:00
3,4,james,james277,james@example.com,hashed277,2023-04-30,2024-05-13 13:15:00
4,5,Alice,alice722,alice@example.com,hashed722,2023-05-15,2024-05-14 14:30:00

1NF

In [ ]:
con.execute("create table Artists(ArtistID INT Primary Key,UserID INT ,Portfolio VARCHAR(255),Specialty VARCHAR(100),Availability VARCHAR(50),Experience VARCHAR(50),FOREIGN KEY(UserID)REFERENCES Users(UserID))")

In [73]:
p=[(1, 1, 'https://portfolio1.com', 'Illustration', 'Full-time', '5 years'),
    (2, 2, 'https://portfolio2.com', 'Graphic Design', 'Part-time', '3 years'),
    (3, 3, 'https://portfolio3.com', 'Animation', 'Freelance', '8 years'),
    (4, 4, 'https://portfolio4.com', 'Digital Painting', 'Full-time', '6 years'),
    (5, 5, 'https://portfolio5.com', 'UI/UX Design', 'Freelance', '4 years')]

In [74]:
query= """INSERT INTO Artists VALUES(?,?,?,?,?,?)"""
con.executemany(query,p)

In [42]:
pd.read_sql("Select * from Artists",con)

,ArtistID,UserID,Portfolio,Specialty,Availability,Experience
0,1,1,https://portfolio1.com,Illustration,Full-time,5 years
1,2,2,https://portfolio2.com,Graphic Design,Part-time,3 years
2,3,3,https://portfolio3.com,Animation,Freelance,8 years
3,4,4,https://portfolio4.com,Digital Painting,Full-time,6 years
4,5,5,https://portfolio5.com,UI/UX Design,Freelance,4 years

In [13]:
con.execute("create table Pricing(PricingID INT PRIMARY KEY , PriceRange VARCHAR(100))")

In [14]:
p=[ (1,'$50-100'),
    (2,'$30-80'),
    (3,'$80-150'),
    (4,'$100-200'),
    (5,'$150-300')]

In [15]:
query= """INSERT INTO Pricing VALUES(?,?)"""
con.executemany(query,p)

In [16]:
pd.read_sql("Select * from Pricing",con)

   PricingID PriceRange
0          1    $50-100
1          2     $30-80
2          3    $80-150
3          4   $100-200
4          5   $150-300

In [17]:
con.execute("create table ArtistSkills(ArtistID INT,SkillID INT,FOREIGN KEY (ArtistID) REFERENCES Artists(ArtistID))")

In [18]:
p=[(1, 1),
    (1, 2),
    (2, 2),
    (2, 3),
    (3, 1)]

In [19]:
query= """INSERT INTO ArtistSkills VALUES(?,?)"""
con.executemany(query,p)

In [20]:
pd.read_sql("Select * from ArtistSkills",con)

   ArtistID  SkillID
0         1        1
1         1        2
2         2        2
3         2        3
4         3        1

In [21]:
 con.execute ("PRAGMA foreign_key = ON")

In [23]:
con.execute("create table pixel(SkillID INT PRIMARY KEY , SkillName VARCHAR(255))")

In [29]:
con.execute("create table Artistsr(ArtistID INT Primary Key,UserID INT ,Portfolio VARCHAR(255),Specialty VARCHAR(100),Availability VARCHAR(50),Experience VARCHAR(50),FOREIGN KEY(UserID)REFERENCES Users(UserID)ON DELETE CASCADE)");

In [43]:
pd.read_sql("Select * from Artists ",con)

,ArtistID,UserID,Portfolio,Specialty,Availability,Experience
0,1,1,https://portfolio1.com,Illustration,Full-time,5 years
1,2,2,https://portfolio2.com,Graphic Design,Part-time,3 years
2,3,3,https://portfolio3.com,Animation,Freelance,8 years
3,4,4,https://portfolio4.com,Digital Painting,Full-time,6 years
4,5,5,https://portfolio5.com,UI/UX Design,Freelance,4 years

In [36]:
pd.read_sql("Select * from userss",con)

,UserID,Name,Username,Email,Password,JoinDate,LastLogin
0,1,John Smith,john123,john@example.com,hashed123,2023-01-15,2024-05-10 08:30:00
1,2,Emily Johnson,emily456,emily@example.com,hashed456,2023-02-20,2024-05-11 10:45:00
2,3,David Brown,david789,david@example.com,hashed789,2023-03-25,2024-05-12 12:15:00
3,4,james,james277,james@example.com,hashed277,2023-04-30,2024-05-13 13:15:00
4,5,Alice,alice722,alice@example.com,hashed722,2023-05-15,2024-05-14 14:30:00

In [50]:
con.execute("DELETE from userss where UserID=2")

In [51]:
pd.read_sql("Select * from userss",con)

,UserID,Name,Username,Email,Password,JoinDate,LastLogin
0,1,John Smith,john123,john@example.com,hashed123,2023-01-15,2024-05-10 08:30:00
1,3,David Brown,david789,david@example.com,hashed789,2023-03-25,2024-05-12 12:15:00
2,4,james,james277,james@example.com,hashed277,2023-04-30,2024-05-13 13:15:00
3,5,Alice,alice722,alice@example.com,hashed722,2023-05-15,2024-05-14 14:30:00

In [53]:
pd.read_sql("Select * from Artists ",con)

,ArtistID,UserID,Portfolio,Specialty,Availability,Experience
0,1,1,https://portfolio1.com,Illustration,Full-time,5 years
1,3,3,https://portfolio3.com,Animation,Freelance,8 years
2,4,4,https://portfolio4.com,Digital Painting,Full-time,6 years
3,5,5,https://portfolio5.com,UI/UX Design,Freelance,4 years

In [60]:
pd.read_sql("Select * from Artists",con)

,ArtistID,UserID,Portfolio,Specialty,Availability,Experience
0,1,1,https://portfolio1.com,Illustration,Full-time,5 years
1,2,2,https://portfolio2.com,Graphic Design,Part-time,3 years
2,3,3,https://portfolio3.com,Animation,Freelance,8 years
3,4,4,https://portfolio4.com,Digital Painting,Full-time,6 years
4,5,5,https://portfolio5.com,UI/UX Design,Freelance,4 years

In [65]:
pd.read_sql("Select * from userss",con)

,UserID,Name,Username,Email,Password,JoinDate,LastLogin
0,1,John Smith,john123,john@example.com,hashed123,2023-01-15,2024-05-10 08:30:00
1,2,Emily Johnson,emily456,emily@example.com,hashed456,2023-02-20,2024-05-11 10:45:00
2,3,David Brown,david789,david@example.com,hashed789,2023-03-25,2024-05-12 12:15:00
3,4,james,james277,james@example.com,hashed277,2023-04-30,2024-05-13 13:15:00
4,5,Alice,alice722,alice@example.com,hashed722,2023-05-15,2024-05-14 14:30:00

In [75]:
pd.read_sql("Select Specialty from Artists where UserID IN (select Distinct UserID from userss where Username ='john123'  )",con)

      Specialty
0  Illustration

In [76]:
pd.read_sql("Select Specialty from Artists where UserID NOT IN (select Distinct UserID from userss where Username ='john123'  )",con)

          Specialty
0    Graphic Design
1         Animation
2  Digital Painting
3      UI/UX Design

In [77]:
pd.read_sql("Select Specialty, Availability from Artists where exists (Select Username from userss where Availability ='Freelance')",con)

      Specialty Availability
0     Animation    Freelance
1  UI/UX Design    Freelance

In [ ]:
#views

In [78]:
con.execute("create View usersx as select Name,username from userss where JoinDate='2023-01-15' ")

In [79]:
pd.read_sql (" select * from usersx",con)

         Name Username
0  John Smith  john123

In [89]:
con.execute("create View usersxx as select Name,username from userss where password='hashed277' ")

In [91]:
pd.read_sql (" select * from usersxx",con)

    Name  Username
0  james  james277

Left,Right and Inner joint

In [ ]:
con.execute("create table ArtistN(ArtistID INT Primary Key,UserID INT ,Portfolio VARCHAR(255),Specialty VARCHAR(100),Availability VARCHAR(50),Experience VARCHAR(50),FOREIGN KEY(UserID)REFERENCES Users(UserID))")

In [ ]:
p=[(1, 1, 'https://portfolio1.com', 'Illustration', 'Full-time', '5 years'),
    (2, 2, 'https://portfolio2.com', 'Graphic Design', 'Part-time', '3 years'),
    (3, 3, 'https://portfolio3.com', 'Animation', 'Freelance', '8 years'),
    (4, 4, 'https://portfolio4.com', 'Digital Painting', 'Full-time', '6 years'),
    (5, 5, 'https://portfolio5.com', 'UI/UX Design', 'Freelance', '4 years')]

In [ ]:
query= """INSERT INTO ArtistN VALUES(?,?,?,?,?,?)"""
con.executemany(query,p)

In [122]:
pd.read_sql("Select * from ArtistN",con)

,ArtistID,UserID,Portfolio,Specialty,Availability,Experience
0,1,1,https://portfolio1.com,Illustration,Full-time,5 years
1,2,7,https://portfolio2.com,Graphic Design,Part-time,3 years
2,3,3,https://portfolio3.com,Animation,Freelance,8 years
3,4,8,https://portfolio4.com,Digital Painting,Full-time,6 years
4,5,5,https://portfolio5.com,UI/UX Design,Freelance,4 years

In [ ]:
con.execute("create table userz (UserID INT PRIMARY KEY  ,Name VARCHAR(100) NOT NULL, Username VARCHAR(50),Email VARCHAR(100),Password VARCHAR(100)NOT NULL,JoinDate DATE,LastLogin TIMESTAMP )")

In [124]:
p=[ (1, 'John Smith', 'john123', 'john@example.com', 'hashed123', '2023-01-15', '2024-05-10 08:30:00'),
    (2, 'Emily Johnson', 'emily456', 'emily@example.com', 'hashed456', '2023-02-20', '2024-05-11 10:45:00'),
    (3, 'David Brown', 'david789', 'david@example.com', 'hashed789', '2023-03-25', '2024-05-12 12:15:00'),
    (4, 'james', 'james277', 'james@example.com', 'hashed277', '2023-04-30','2024-05-13 13:15:00'),
    (5, 'Alice', 'alice722', 'alice@example.com', 'hashed722', '2023-05-15','2024-05-14 14:30:00')];

In [125]:
query= """INSERT INTO userz VALUES(?,?,?,?,?,?,?)"""
con.executemany(query,p)

In [126]:
pd.read_sql("Select * from userz",con)

,UserID,Name,Username,Email,Password,JoinDate,LastLogin
0,1,John Smith,john123,john@example.com,hashed123,2023-01-15,2024-05-10 08:30:00
1,2,Emily Johnson,emily456,emily@example.com,hashed456,2023-02-20,2024-05-11 10:45:00
2,3,David Brown,david789,david@example.com,hashed789,2023-03-25,2024-05-12 12:15:00
3,4,james,james277,james@example.com,hashed277,2023-04-30,2024-05-13 13:15:00
4,5,Alice,alice722,alice@example.com,hashed722,2023-05-15,2024-05-14 14:30:00

In [127]:
pd.read_sql("select * from userz RIGHT JOIN ArtistN on userz.UserID=ArtistN.UserID",con)

,UserID,Name,Username,Email,Password,JoinDate,LastLogin,ArtistID,UserID,Portfolio,Specialty,Availability,Experience
0,1.0,John Smith,john123,john@example.com,hashed123,2023-01-15,2024-05-10 08:30:00,1,1,https://portfolio1.com,Illustration,Full-time,5 years
1,3.0,David Brown,david789,david@example.com,hashed789,2023-03-25,2024-05-12 12:15:00,3,3,https://portfolio3.com,Animation,Freelance,8 years
2,5.0,Alice,alice722,alice@example.com,hashed722,2023-05-15,2024-05-14 14:30:00,5,5,https://portfolio5.com,UI/UX Design,Freelance,4 years
3,NaN,None,None,None,None,None,None,2,7,https://portfolio2.com,Graphic Design,Part-time,3 years
4,NaN,None,None,None,None,None,None,4,8,https://portfolio4.com,Digital Painting,Full-time,6 years

In [128]:
pd.read_sql("select * from userz LEFT JOIN ArtistN on userz.UserID=ArtistN.UserID",con)

,UserID,Name,Username,Email,Password,JoinDate,LastLogin,ArtistID,UserID,Portfolio,Specialty,Availability,Experience
0,1,John Smith,john123,john@example.com,hashed123,2023-01-15,2024-05-10 08:30:00,1.0,1.0,https://portfolio1.com,Illustration,Full-time,5 years
1,2,Emily Johnson,emily456,emily@example.com,hashed456,2023-02-20,2024-05-11 10:45:00,NaN,NaN,None,None,None,None
2,3,David Brown,david789,david@example.com,hashed789,2023-03-25,2024-05-12 12:15:00,3.0,3.0,https://portfolio3.com,Animation,Freelance,8 years
3,4,james,james277,james@example.com,hashed277,2023-04-30,2024-05-13 13:15:00,NaN,NaN,None,None,None,None
4,5,Alice,alice722,alice@example.com,hashed722,2023-05-15,2024-05-14 14:30:00,5.0,5.0,https://portfolio5.com,UI/UX Design,Freelance,4 years

In [129]:
pd.read_sql("select * from userz INNER JOIN ArtistN on userz.UserID=ArtistN.UserID",con)

,UserID,Name,Username,Email,Password,JoinDate,LastLogin,ArtistID,UserID,Portfolio,Specialty,Availability,Experience
0,1,John Smith,john123,john@example.com,hashed123,2023-01-15,2024-05-10 08:30:00,1,1,https://portfolio1.com,Illustration,Full-time,5 years
1,3,David Brown,david789,david@example.com,hashed789,2023-03-25,2024-05-12 12:15:00,3,3,https://portfolio3.com,Animation,Freelance,8 years
2,5,Alice,alice722,alice@example.com,hashed722,2023-05-15,2024-05-14 14:30:00,5,5,https://portfolio5.com,UI/UX Design,Freelance,4 years